version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "54321:80"
    restart: unless-stopped

  backend_service:
    depends_on:
      - postgres
    image: daaj/ultraprofile:0.0.1
    environment:
      DB_HOST: "postgres:5432"
    ports:
      - "8000:8000"
    restart: always

volumes:
  postgres:
  pgadmin: