"""feat: new table adress

Revision ID: 083f7e65900d
Revises: eb4c14dffca7
Create Date: 2023-01-03 20:28:46.924499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '083f7e65900d'
down_revision = 'eb4c14dffca7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('bug_tracker_url', sa.String(), nullable=True),
    sa.Column('who', sa.String(), nullable=True),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bug_tracker_url')
    )
    op.create_index(op.f('ix_adress_profile_id'), 'adress', ['profile_id'], unique=False)
    op.drop_index('ix_bug_profile_id', table_name='bug')
    op.drop_table('bug')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bug_tracker_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('who', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('when', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name='bug_profile_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bug_pkey'),
    sa.UniqueConstraint('bug_tracker_url', name='bug_bug_tracker_url_key')
    )
    op.create_index('ix_bug_profile_id', 'bug', ['profile_id'], unique=False)
    op.drop_index(op.f('ix_adress_profile_id'), table_name='adress')
    op.drop_table('adress')
    # ### end Alembic commands ###
